rootProject.name = "Server"
include("brightnessService")
include("common")
include("greenhouseService")
include("greenhouseCommunicationGateway")
include("soilMoistureService")
include("humidityService")
include("temperatureService")
include("operationService")
include("clientCommunicationGateway")
